name: Create Git tag on merge

on:
  pull_request:
    types: [closed]

jobs:
  create_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release version
        run: |
          VERSION=$(cat version)
          if ! git rev-parse v${VERSION} > /dev/null 2>&1; then
            git tag v${VERSION}
            git push origin v${VERSION}
          fi
